spring.application.name=MobileAPI

spring.datasource.url=jdbc:postgresql://localhost:15432/my_database
spring.datasource.username=my_user
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=localhost
spring.data.redis.port=16379

jwt.secret=2L4kDd9f$XyP!ZpQ7sMpUcvHWt9LfHq8